### ISSUE TITLE
Consider adding `params.yaml` file as a possible replacement of `params.ini`

### ISSUE THREAD

**Issue by yakutovicha** [Probe-Particle/ppafm#153]

**Comment by ProkopHapala** [comment]
There is nothing yet, but I'm already very much pro

**Comment by NikoOinonen** [comment]
Since we are now moving towards using the `toml` file format, I'm thinking we could make use of the flexible structure of this file format to add more clarity to how the parameters are defined.

Right now we are just using the file format as one long list like we did with the old `.ini`, but the `toml` format allows for categorization of the parameters, so we could do something like
```toml
[tip]
charge = -0.1
probeType = "O"

[scan]
scanStep = [ 0.1, 0.1, 0.1,]
scanMin = [ 0.0, 0.0, 5.0,]
scanMax = [ 22.0, 22.0, 9.0,]
```
I think we could also use this opportunity to perhaps rethink the naming on some of the parameters, for better clarity, as well as try to better standardize it across the different user interfaces that we have. For example, I already mentioned in some comment in #275 that the parameter names currently don't have any consistent format, being a mixture of UPPER, lower, snake_case and CamelCase. We should pick just one.
